const products=[
{id:1,cat:'מקררים',brand:'Samsung',name:'מקרר Bespoke 4 דלתות',desc:'עיצוב מודולרי, קור אחיד ומגירת חטיפים אסטרטגית.',price:3490,rating:4.9,emoji:'🧊',badge:'בחירת צביקה',features:['נפח 647 ליטר','מערכת No Frost','Wi‑Fi ושליטה מהנייד']},
{id:2,cat:'כביסה',brand:'LG',name:'מכונת כביסה AI DD',desc:'בגדים נקיים, פחות דרמה. כולל מנוע שקט במיוחד.',price:2290,rating:4.8,emoji:'🫧',badge:'מבצע',features:['קיבולת 9 ק״ג','15 תוכניות','מנוע Direct Drive']},
{id:3,cat:'טלוויזיות',brand:'Sony',name:'טלוויזיית Bravia XR 55״',desc:'תמונה חדה כל כך שאפשר לראות מי לקח את השלט.',price:2790,rating:4.9,emoji:'📺',badge:'חדש',features:['4K HDR','Google TV','Dolby Vision']},
{id:4,cat:'מטבח',brand:'Bosch',name:'מדיח כלים Serie 4',desc:'מנקה אחרי ארוחת שישי. גם את הסיר ההוא.',price:1890,rating:4.7,emoji:'🍽️',features:['12 מערכות כלים','שקט 46dB','תוכנית מהירה']},
{id:5,cat:'מטבח',brand:'Smeg',name:'תנור Multifunction',desc:'אופה, צולה ומעלה את הרף לארוחת ערב.',price:3190,rating:4.8,emoji:'🔥',badge:'אהוב',features:['72 ליטר','10 פונקציות','ניקוי אדים']},
{id:6,cat:'מיזוג',brand:'Tadiran',name:'מזגן Alpha Pro 1.25 כ״ס',desc:'קריר, חסכוני ובעיקר לא מתווכח עם הקיץ.',price:1790,rating:4.9,emoji:'❄️',badge:'30% הנחה',features:['תפוקה 10,200 BTU','דירוג אנרגטי A','Wi‑Fi מובנה']},
{id:7,cat:'ניקיון',brand:'Dyson',name:'שואב אבק V12 Detect',desc:'מוצא אבק שלא ידעתם שקיים. עכשיו אתם יודעים.',price:2490,rating:4.8,emoji:'🧹',features:['עד 60 דקות עבודה','מסנן HEPA','תאורה לזיהוי אבק']},
{id:8,cat:'קטנים',brand:'Ninja',name:'אייר פרייר Foodi',desc:'פריך מבחוץ, עסיסי מבפנים, מינימום שמן ובלגן.',price:699,rating:4.7,emoji:'🍟',badge:'מחיר שדו',features:['קיבולת 5.2 ליטר','6 תוכניות','סל רחיץ במדיח']},
{id:9,cat:'קטנים',brand:'DeLonghi',name:'מכונת קפה Magnifica',desc:'קפה של בית קפה, בלי לחפש חניה ובלי בריסטה ששופט.',price:1890,rating:4.9,emoji:'☕',features:['טחינה במקום','מקציף חלב','3 דרגות חוזק']},
{id:10,cat:'מיזוג',brand:'Electra',name:'מאוורר מגדל Smart',desc:'זרימת אוויר חכמה למי שאוהב רוח אבל לא הוריקן.',price:429,rating:4.6,emoji:'🌀',features:['3 מהירויות','טיימר 12 שעות','שלט רחוק']}
];
let cart=JSON.parse(localStorage.getItem('shadoCart')||'[]'), activeCat='all';
const $=s=>document.querySelector(s), money=n=>'₪'+n.toLocaleString('he-IL');
function render(){const q=$('#search').value.toLowerCase(),cat=$('#category').value,brand=$('#brand').value,sort=$('#sort').value;let arr=products.filter(p=>(activeCat==='all'||p.cat===activeCat)&&(cat==='all'||p.cat===cat)&&(brand==='all'||p.brand===brand)&&(`${p.name} ${p.brand} ${p.desc}`.toLowerCase().includes(q)));if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);if(sort==='rating')arr.sort((a,b)=>b.rating-a.rating);$('#products').innerHTML=arr.map(p=>`<article class="product"><div class="product-img">${p.badge?`<span class="badge">${p.badge}</span>`:''}<span>${p.emoji}</span></div><div class="product-body"><span class="product-brand">${p.brand} · ${p.cat}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="rating">★★★★★ <span>${p.rating}</span></div><div class="price"><b>${money(p.price)}</b><button class="add" data-add="${p.id}">הוספה לסל</button></div><button class="detail" data-detail="${p.id}">פרטים נוספים ←</button></div></article>`).join('');$('#empty').style.display=arr.length?'none':'block';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>details(+b.dataset.detail));}
function renderCart(){let total=0;$('#cartItems').innerHTML=cart.length?cart.map((x,i)=>{let p=products.find(y=>y.id===x.id);total+=p.price*x.qty;return `<div class="cart-line"><span class="emoji">${p.emoji}</span><div><h4>${p.name}</h4><small>${money(p.price)} · ${x.qty} יח׳</small></div><div class="qty"><button data-minus="${i}">−</button><b>${x.qty}</b><button data-plus="${i}">＋</button></div></div>`}).join(''):'<p style="color:var(--muted);text-align:center;padding:45px 0">הסל ריק, אבל זה מצב זמני בהחלט 😉</p>';$('#cartTotal').textContent=money(total);$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);localStorage.setItem('shadoCart',JSON.stringify(cart));document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(+b.dataset.minus,-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(+b.dataset.plus,1));}
function add(id){let x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id,qty:1});renderCart();toast('נוסף לסל — צביקה שומר לך אחד! 🛒');}
function change(i,n){cart[i].qty+=n;if(cart[i].qty<1)cart.splice(i,1);renderCart()}
function details(id){let p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-product"><div class="product-img">${p.emoji}</div><div><span class="product-brand">${p.brand} · ${p.cat}</span><h2>${p.name}</h2><p>${p.desc}</p><ul>${p.features.map(x=>`<li>✓ ${x}</li>`).join('')}</ul><b style="font:900 23px Rubik;color:var(--blue)">${money(p.price)}</b><br><button class="btn primary" style="margin-top:15px" data-modal-add="${p.id}">צביקה, שמור לי אחד!</button></div></div>`;$('#modal').classList.add('show');$('[data-modal-add]').onclick=()=>{add(id);$('#modal').classList.remove('show')};}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2400)}
products.forEach(p=>{if(![...$('#brand').options].some(o=>o.value===p.brand))$('#brand').insertAdjacentHTML('beforeend',`<option>${p.brand}</option>`)});['search','category','brand','sort'].forEach(id=>$('#'+id).oninput=render);document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));$('#category').value='all';render()});$('#cartOpen').onclick=()=>$('#cart').classList.add('open');$('#cartClose').onclick=()=>$('#cart').classList.remove('open');document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('#modal').classList.remove('show'));$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};$('#checkout').onclick=()=>{if(!cart.length)return toast('הסל עוד ריק — צביקה מחכה בסבלנות 😉');toast('קיבלנו! צביקה יחזור אליך לתיאום 📞');$('#cart').classList.remove('open')};$('#contactForm').onsubmit=e=>{e.preventDefault();$('#formMsg').textContent='ההודעה נשלחה! צביקה יחזור אליך בהקדם.';e.target.reset()};$('#menuBtn').onclick=()=>{let n=document.querySelector('nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='82px';n.style.right='0';n.style.left='0';n.style.background='#fff';n.style.padding='20px';n.style.flexDirection='column'};render();renderCart();
